language: go
os:
  - linux
go:
  - 1.13
install:
  - go get -t -v -d ./...
script:
  - go test -v .
  - go test -coverpkg=./ -coverprofile=coverage.data -timeout=5s ./
  - go tool cover -func=coverage.data -o coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash)